# This BDD feature file corresponds to the Go fuzz test file:
# ./hclwrite/fuzz/fuzz_test.go
#
# It covers the following Go fuzz test:
# - FuzzParseConfig

Feature: HCL Write Parser Fuzzing
  This feature describes the properties being tested by fuzzing the HCL configuration parser
  in the `hclwrite` package. The goal is to ensure that any input successfully parsed
  can also be written out without errors, indicating internal consistency.

  Background:
    Given a HCL writing context

  Scenario: Successfully parsed HCL configuration can be written
    This scenario captures the core property tested by FuzzParseConfig.
    The fuzzer generates various byte inputs. If an input is successfully parsed
    by `hclwrite.ParseConfig` without any diagnostics indicating errors,
    then the resulting `hclwrite.File` object should be serializable
    (e.g., via `file.WriteTo()`) without causing a runtime error or panic.

    Given an arbitrary byte stream as input for HCL configuration
    When `hclwrite.ParseConfig` attempts to parse the input
    And the parsing succeeds without errors
    Then serializing the parsed HCL file using `file.WriteTo` should also succeed without error

  Scenario: Parsing invalid HCL configuration may produce diagnostics
    This scenario acknowledges that the fuzzer will also generate inputs
    that are not valid HCL. In such cases, `hclwrite.ParseConfig` is expected
    to return diagnostics.

    Given an arbitrary byte stream as input for HCL configuration
    When `hclwrite.ParseConfig` attempts to parse the input
    And the input is not valid HCL syntax
    Then the parser should return diagnostics indicating the errors

  Scenario: Fuzzer aims to find inputs that parse but fail to write
    This scenario clarifies the failure condition the fuzzer is designed to detect.
    A failure in `FuzzParseConfig` occurs if an input is parsed successfully
    (no diagnostics from `hclwrite.ParseConfig`) but then the subsequent
    `file.WriteTo` operation results in an error.

    Given the HCL parser fuzzer `FuzzParseConfig`
    When it processes a stream of generated byte inputs
    Then the fuzzer should report a failure if an input is parsed by `hclwrite.ParseConfig` without error,
    but the subsequent call to `file.WriteTo` on the resulting `hclwrite.File` returns an error.
    And such a failure indicates a potential bug in the HCL writing or parsing logic.
